baseurl = "https://deeeet.com"
title = "Taichi Nakashima"
languageCode = "ja-jp"
copyright = "Copyright © 2013-2020 Taichi Nakashima"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
pygmentsuseclasses = true

[permalinks]
    writing = "/writing/:year/:month/:day/:filename/"
    
[author]
    name = "Taichi Nakashima"
    image = "bio.jpeg"
    bio = "Microservices Platform Team at Mercari, Inc.."
    
[params]
    cover_image = "cover-201412.jpg"
    twitter = "deeeet"
    github = "tcnksm"
    google_font = "Inter:900,700,400"

    [params.sharing]
        twitter =true
        hn = true
        
    [params.analytics]
        googleid = "UA-45390253-1"