baseurl = "https://deeeet.com"
title = "SOTA"
languageCode = "ja-jp"
copyright = "Copyright (C) 2013-2020 Taichi Nakashima All Right Reserved."

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
pygmentsuseclasses = true

[permalinks]
    writing = "/writing/:year/:month/:day/:filename/"
    
[author]
    name = "Taichi Nakashima"
    image = "bio.jpeg"
    bio = "Microservices Platform Team at Mercari, Inc.. Please contact me via twitter."
    
[params]
    cover_image = "cover-201412.jpg"
    twitter = "deeeet"
    github = "tcnksm"
    google_font = "Lato:900"

    [params.sharing]
        twitter =true
        hn = true
        
    [params.analytics]
        googleid = "UA-45390253-1"