#cloud-config

coreos:
  etcd:
    # curl -w "\n" https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/b2f4664ea4a971c3bd267db642d9b0c7
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
      
  fleet:
    # used for fleetctl ssh command
    public-ip: $private_ipv4
    metadata: role=web
  
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start